### ISSUE TITLE
Problem getting state text

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/smarthome.paperui#11]
moved over from https://github.com/openhab/openhab2/issues/229 - see there for details

**Comment by dnobel** [comment]
Unfortunately I´m not able to reproduce this bug. @mathiasimmer Does it still occur with the latest version of the Paper UI? Can you provide more information on how to reproduce it?

**Comment by mathiasimmer** [comment]
@dnobel Yes, last time I checked, it worked in the latest build. Don't know exactly what fixed it though. Might have been a mix-match of libraries.

**Comment by dnobel** [comment]
If not reproducible any more I tend to close this issue. Otherwise please reopen the issue.
