### ISSUE TITLE
Numbers are sent as Strings within configurations when creating new Things

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/smarthome.paperui#15]
When manually creating a new Thing through the Paper UI, integer values are sent as a String within the JSON to the REST API. This results in invalid configurations, see https://github.com/openhab/openhab2/issues/258

**Comment by kaikreuzer** [comment]
@sja Any chance for you to look at this? It is a rather nasty and critical bug, see https://github.com/openhab/openhab2/issues/258 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=465428.

**Comment by dnobel** [comment]
If not, I can try to fix that today.

**Comment by dnobel** [comment]
Fixed with new Paper UI contribution.

**Comment by sja** [comment]
I'd like to delete my fork, because it's from eclipse/smarthome. My new fork would be from openhab/smarthome.
Do I kill the PR with that action? Or did you copied the stuff?

**Comment by kaikreuzer** [comment]
As this PR is already closed, it does not really matter. The fix is already on master.
