### ISSUE TITLE
required bundle javax.servlet

### ISSUE THREAD

**Issue by maggu2810** [openhab/smarthome.paperui#19]
The javax.servlet dependency should be moved from "Require-Bundle" to "Import-Package".
Same as here https://bugs.eclipse.org/bugs/show_bug.cgi?id=475876 but f

https://github.com/openhab/smarthome.paperui/blob/master/extensions/ui/org.eclipse.smarthome.ui.paperui/META-INF/MANIFEST.MF#L15

**Comment by dnobel** [comment]
The bundle was originally copied form the Classic UI bundle. As commented in the bugzilla issue, I guess it is a mistake and can be turned into package import

**Comment by maggu2810** [comment]
Solved with #20
