### ISSUE TITLE
Wrong detection of Discovery-Enabled Bindings

### ISSUE THREAD

**Issue by sja** [openhab/smarthome.paperui#2]
On setup wizard, my binding is labled as "Binding does not support discovery." The scope's value of discoverySupported is false. But on a call to `http://localhost:8080/rest/discovery`, my BindingID is listed correctly.

**Comment by dnobel** [comment]
That´s indeed strange. In which view exactly? After you have chosen a thing type?

**Comment by sja** [comment]
My fault. The url state was `#/setup/wizard/search/myBinding` which seemed to come from `ESH-INF/binding/binding.xml` but I renamed stuff to myXY. After updating the binding.xml, the state was `#/setup/wizard/search/myXY` and everything was correct.
