### ISSUE TITLE
PaperUI does not allow to assign bridges to rooms, and does not show bridges in Control section

### ISSUE THREAD

**Issue by JochenHiller** [openhab/smarthome.paperui#21]
We are using PaperUI for a binding, which has a bridge with lots of channels.
PaperUI does actually NOT allow
* to give bridge a name
* to assign a bridge to a room
* to see the items of a bridge in Control section of UI

We think it makes sense to support that for bridges too.

**Comment by dnobel** [comment]
I'm wondering, because giving it a name and showing it in the Control UI should actually work. But I also agree for the room. Will check that later.

**Comment by dnobel** [comment]
Fixed with https://github.com/openhab/smarthome.paperui/commit/ef7acca55dd59ac89cffc0114f986204163f09be.
