### ISSUE TITLE
Update Paper UI to Angular Material 0.10.1

### ISSUE THREAD

**Issue by dnobel** [openhab/smarthome.paperui#22]

**Comment by dnobel** [comment]
Here you see two Screenshots.

Looks like the new tab bar is not styled and besides that I think we need to adapt some font sizes. The rest looks fine.

![paperui1](https://cloud.githubusercontent.com/assets/1380535/9710222/35eeaf44-5538-11e5-923d-8a3cb7200aa1.png)
![paperui2](https://cloud.githubusercontent.com/assets/1380535/9710221/35ee2d6c-5538-11e5-839b-b2ae820dbb0b.png)

**Comment by dnobel** [comment]
Here is a video, where you can see that switching the tabs is relatively fast: https://drive.google.com/open?id=0BxtonT6WSF2-YW5KUHp3Wi1nZDA

**Comment by joepadmiraal** [comment]
I did mvn package and deployed my version to another machine.
There I see the same issue as in your screenshot (no background color on the tab bar).
The weird thing is that other style changes do seem to get through.

When I run openhab from Eclipse it does look fine:
<img width="1273" alt="screen shot 2015-09-07 at 10 36 47" src="https://cloud.githubusercontent.com/assets/1912949/9712831/cd72447e-554d-11e5-9df3-69959abba4c5.png">

I did notice a css issue with the tab bar when running with my version on real devices or on Chrome with a small window. I'll look into that as soon as the other tab css changes working.

**Comment by joepadmiraal** [comment]
I added some css to also style the background of the tab header from the smarthome-paperui project and verified the mvn package process is also including it.

So now I'll start looking at the small window issue.

**Comment by joepadmiraal** [comment]
The small window issue is now fixed in my repo.
So as far as I can see all visual issues are solved now.
I think performance still is a thing we can improve, but that might need a new ticket.

**Comment by dnobel** [comment]
Thanks. I checked it, but the tabs were orange :). The original Paper UI is blue and just gets it orange style through the openHAB theme fragment.

I created a small PR to fix this and some other small layout fixes: https://github.com/joepadmiraal/smarthome.paperui/pull/1

But the performance for rendering the control area seems to be real bad (as I feared). If I add a few things, it takes up to 5 seconds to render control. Moreover the favicon is flashing. But switching tabs is very fast.

I can take a look later to figure out what might be the problem.

**Comment by joepadmiraal** [comment]
Cool.

I changed the tab loading a bit so it only loads the items of the active tab.
This is how it worked before the material update and seems faster.
Ultimately we can load all items once instead on every tab switch.

**Comment by joepadmiraal** [comment]
One more thing.
How do you test paper-ui without openhab?

**Comment by dnobel** [comment]
I just use the ESH development environment and import the Paper UI bundle into it. If you want to test with openHAB just exclude the Paper UI Theme fragment from the Runtime Configuration.

**Comment by joepadmiraal** [comment]
I want to test without openhab so I get the blue version you are using.
How does that work?

**Comment by kaikreuzer** [comment]
You can do that test from the openHAB2 IDE as well by simply closing the org.openhab.ui.paperui project in the workspace.

**Comment by dnobel** [comment]
@joepadmiraal I created a another small PR to fix the masonry rendering, but the rest looks good to me. If you want you can create a PR against this repo. Thank you very much!

**Comment by joepadmiraal** [comment]
Great!
I created PR #23

**Comment by joepadmiraal** [comment]
I had to do a small change in the org.openhab.ui.paperui themes.css file in order to get the blue tab background to orange.
It seems the patch folder of that project exists in the .gitignore file.
Should I do the change in another place?
Or is the .gitignore wrong?

**Comment by dnobel** [comment]
I finally merged the PR. @joepadmiraal Thanks a lot for your help. The change in the theme.css file needs to be contributed to the openHAB2 project (https://github.com/openhab/openhab2/blob/master/addons/ui/org.openhab.ui.paperui/patch/web/css/theme.css). The next openHAB2 build will automatically get the new Paper UI.

**Comment by dnobel** [comment]
Just one remark: as the CQ for ESH was for version 0.10.0 I downgraded the version. But it seems there are no problems. I guess most changes came from 0.9 and 0.10.0.

**Comment by joepadmiraal** [comment]
@dnobel The theme.css file you're referring to is the same file as I am referring to.
It's excluded from git by this [.gitingore]https://github.com/openhab/openhab2/blob/master/addons/ui/org.openhab.ui.paperui/.gitignor)

**Comment by dnobel** [comment]
Sorry, if it is really exluded by the gitignore it must be wrong. So you can fix that aa well

**Comment by joepadmiraal** [comment]
I checked it again. I was wrong, the gitignore does not exclude it.
I created a [pullrequest](https://github.com/openhab/openhab2/pull/403) for the theme.css.
