### ISSUE TITLE
Contribute code to Eclipse SmartHome

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/smarthome.paperui#3]
As this is only a temporary location for the PaperUI, preparations need to be done to move it to the official repo of Eclipse SmartHome.

**Comment by kaikreuzer** [comment]
Created the following CQs:
- CQ9929: AngularJS 1.3.13
- CQ9930: angular-material 0.10.0
- CQ9931: angular-route 1.3.13
- CQ9932: angular-resource 1.3.13
- CQ9933: sprintf 1.0.3
- CQ9934: jquery 2.1.3
- CQ9935: Bootstrap 3.3.2
- CQ9936 TinyColors 1.1.2
- CQ9937 Masonry 3.3.1
- CQ9938 Roboto Fontface 0.4.3

**Comment by xsnrg** [comment]
Kai, does this mean PaperUI issues should be opened against Eclipse Smarthome and not here?

**Comment by kaikreuzer** [comment]
No, for the time being, i.e. as long as the code is maintained here, issues should be entered here as well.

**Comment by maggu2810** [comment]
What is missing here?
Do we still wait for CQ9938?

**Comment by kaikreuzer** [comment]
Correct.

**Comment by kaikreuzer** [comment]
All CQs are approved for checkin, so I hand over to you!

@sja, how many unmerged changes do you currently have? When do you consider to have it all contributed and merged here, so that a PR against Eclipse can be created?

**Comment by sja** [comment]
@kaikreuzer You mean my local changes or the diff between some old/new forks/repos?

**Comment by kaikreuzer** [comment]
What ever you are currently working on and want to merge before the code is moved.

**Comment by sja** [comment]
Ah, ok. You mean this is the last chance to make quick changes. Then move it as it is. I'm very very busy atm and the earliest date would be in 2-3 weeks.

**Comment by kaikreuzer** [comment]
Busy on Paper UI changes?

**Comment by sja** [comment]
Nope. Compensating colleagues on Holiday. :-)

**Comment by kaikreuzer** [comment]
Ok, so I hand over to @dnobel: Please feel free to create a PR at ESH anytime (when you feel it is best), I will then do the CQ for it.

**Comment by dnobel** [comment]
Yes I will do that.

**Comment by kaikreuzer** [comment]
Hm, just noted that I missed a CQ in the list above, for the Google icon set: CQ 10013.
This isn't yet approved. Still, we can continue with the PR for the PaperUI and hope that both get approved at the same time.

**Comment by dnobel** [comment]
I´m preparing the contribution to ESH right now. @joepadmiraal : As you contributed to the Paper UI you will be mentioned as Co-Author in the PR (together with some others). Could I ask you to give me your real name and to sign a CLA (if you do not already have one): https://eclipse.org/legal/CLA.php

This is needed for the legal IP process of the Eclipse Foundation. You can also find more information here: https://www.eclipse.org/smarthome/documentation/community/contributing.html#conventions-for-pull-requests

**Comment by joepadmiraal** [comment]
@dnobel I signed the CLA.
My real name is: Joep Admiraal

Thanks for including me as co-author :)

**Comment by dnobel** [comment]
@joepadmiraal : Thanks, just noticed that I also need your E-Mail which you signed the CLA with. Then I will create the PR.

**Comment by joepadmiraal** [comment]
@dnobel my mail address is my first name with groovytunes.nl as the domain name.

**Comment by dnobel** [comment]
Thanks!

**Comment by dnobel** [comment]
Ok, branch is ready: https://github.com/eclipse/smarthome/compare/eclipse:master...dnobel:paper-ui?expand=1

Just waiting for feedback on #24 if it should become pat of the initial PR.

**Comment by dnobel** [comment]
OK, PR is created including #24.

**Comment by kaikreuzer** [comment]
merged.
