### ISSUE TITLE
Support more configuration features

### ISSUE THREAD

**Issue by dnobel** [openhab/smarthome.paperui#4]
At the moment the following configuration features are not yet supported:

* Option list not supported
* Context not supported
* Minimum and maximum not supported
* Filter not supported
* Configuration groups

**Comment by dnobel** [comment]
@sja I already began working on that. I will create a rendering model inferred from the config description,which is then used in the template.

**Comment by dnobel** [comment]
This PR added a few of the mentioned features:

https://github.com/openhab/smarthome.paperui/pull/7

* -Option list not supported-
* -Context not supported- (at least for password)
* Minimum and maximum not supported
* Filter not supported 
* Configuration groups

**Comment by kaikreuzer** [comment]
moved to https://github.com/eclipse/smarthome/issues/566
